// Code generated by mockery v2.33.0. DO NOT EDIT.

package mocks

import (
	context "context"

	client "go-micro.dev/v4/client"

	devicev1 "github.com/jinmukeji/huimaibao-proto/gen/go/huimaibao/biz/device/v1"

	mock "github.com/stretchr/testify/mock"
)

// DeviceAPIService is an autogenerated mock type for the DeviceAPIService type
type DeviceAPIService struct {
	mock.Mock
}

// ListDevices provides a mock function with given fields: ctx, in, opts
func (_m *DeviceAPIService) ListDevices(ctx context.Context, in *devicev1.ListDevicesRequest, opts ...client.CallOption) (*devicev1.ListDevicesResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *devicev1.ListDevicesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *devicev1.ListDevicesRequest, ...client.CallOption) (*devicev1.ListDevicesResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *devicev1.ListDevicesRequest, ...client.CallOption) *devicev1.ListDevicesResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*devicev1.ListDevicesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *devicev1.ListDevicesRequest, ...client.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDeviceAPIService creates a new instance of DeviceAPIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceAPIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceAPIService {
	mock := &DeviceAPIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
